---

- hosts: all
  become: true
  tasks:

    #the following code is valid for both centos and ubuntu

  - name: install apache & php packages
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes 

