---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution in ["centOS", "Fedora"]  
        #when: ansible_distribution == "Ubuntu" 
        #when: ansible_distribution_version == "8.2"
  - name: install nginx package
    dnf:
      name: nginx
      state: absent
    when: ansible_distribution in ["Ubuntu", "Fedora"]
  

  - name: update repository index
    :
      update_cache: yes
    when: ansible_distribution in ["centOS", "Fedora"]
        #when: ansible_distribution == "Ubuntu" 
        #when: ansible_distribution_version == "8.2"
  - name: install nginx package
    dnf:
      name: nginx
      state: absent
    when: ansible_distribution in ["Ubuntu", "Fedora"]



