---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    dnf:
      update_cache: yes  
      state: latest

  - name: install apache2 package
    dnf:
      name: httpd
      state: latest
  


