---

- hosts: all
  become: true
  pre_tasks: 

  - name: install updates  on CentOS and Fedora servers
    tags: always
    yum:  
      update_only: yes
      update_cache: yes
    when: ansible_distribution in ["CentOS", "Fedora"]

  - name: isntall updates on ubuntu or debian
    tags: always
    apt: 
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"] 


  - name: install apache and php for Ubuntu servers
    tags: apache, ubuntu, apache2
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"


  - name: install apache and php for CentOS servers
    tags: apache, centos, httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "Fedora"
  

- hosts: web_servers
  become: true
  tasks: 

  - name: copy default html file to servers
    copy:
      src: default_sites.html
      dest: /var/www/html/index.html
      owner: abdul
      group: abdul
      mode: 0644


- hosts: active_servers
  become: true
  gather_facts: no
  tasks:

  - name: install mariadb package (fedora)
    dnf:
      name: mariadb
      state: latest

  - name: install unzip (fedora)
    package: 
      name: unzip

  - name: install terraform (fedora)
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: abdul
      group: abdul
